version: '3.8'
services:
  app:
    build: .
#    env_file: /opt/flight_tracker/config/.env
#    ports:
#      - "8080:8080"
#    restart: unless-stopped
#    environment:
#      - ENV=production
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge