name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Go modules
        run: | 
          docker run --rm -v $(pwd):/app -w /app golang:1.21-alpine go mod tidy
          docker run --rm -v $(pwd):/app -w /app golang:1.21-alpine go mod verify

#      - name: Stop and remove old container
#        run: |
#          docker stop my-app || true
#          docker rm my-app || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d 

      - name: Clean up old imag
        run: |
          docker image prune -f